language: go

sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - secure: "EJMYq/6K2RLp+DbzZnDEyaQ8FUoKg0NsRc9V3eJbqfdy70jdTNj8zyf0zyVKJmmsKWr+iaBxRsEVCrGkqKp17sWZi5595UnMLrYjRMJbHtOHNNSrzMAGIrGMp98RHAUStU2E8BUdttKejbQIYjWIJzjqIAIRTXKMRKVtjgf/D1+y40njLm8bbi3hoLKtDwJq3OOf6SUvEJ4/7Z3IRsUxwMSzBE/p+xPPknhdtYsF4cHdDRIxhDE7dhg13jvhBNrDenNHFXrDqxF6B+a4XM6XVdwMHOKSP/euSFaD5zf4sseWT/gWwmbMkR37UoKD54Sl3uIpCNm53LbhKvNelpeS4tOXMvkj7yKm2lo2ouVsZBdzrsZWHINaqr4BQCSyWp/fUOVHstIrKfwg5YuxXWpUTpezqhJFam+oA8z1L/T/0B2w5Dj4BmxgXOBnmNFcaEhI/IQ7UzWbhxaSmzfnHDZJQKox9N6n21phOeCgw9KY1seTcRSL56ceGHITOtB9f2f0zRTnNczGzIhmq1p1vvihwpWU9Zd9l3ZDvhQjoZmB+mm5/rEeP/MaWwucU4zEqapzIHMg3IrTW/LnkYBTG3uJJ6gKCiJOSxf/zir2D43Lo1SHuPYDqERUYhb4xy/V3PzpbafyA0GARuW8CDC0cmM6cxXO9j2Uc/eEco9FnS2xwrc="


# skip the `go get` stuff, since we do all of that in Docker
install: true

before_script:
  - export

script:
  - ./travis-build.sh
