language: go

sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - secure: "R3mp32hYJoXW2cIR3m78fkhTQCka4dKKNdugCE0VlbR47d8aKoRmpPeoArf1qYKw/hIrQKt9S+LaREaOso1BOlCCLknnnXtyrGf3P1hmdSlC5HP5uSo4kgu+ZV/O/8UO1zAzt+oATgRUOUzrX0JFR2xd+UZdw/mzEtJnw/gF74vBOwas6vI1RID9B578tOtaSbvfmphhmntmk06aIBgH9ThnYhIm+ZxKwKuP0ldiG5CDhwwhXVbb9Nl7mJXCtAHdQxG8XdwZKjOgfLBLH02oHxZgsYf3oelZcnuPaA5jwO3y/rjkt+mapZVs6/GeVJ35XeUrGDUnkZqGjZM3SdKtB0wND8C3cjInyCjyg8SYXx3xWEp0cVgya1KuggTfCs7RKR9T24iOnSaGgZOwkuJ+ZUcd7GuMyx1wL/2CC2tHcslej2GGlgSia7XzPxTo7f8rWiUyePP7WP0qO9F+FpZU36y9ywhsmJj9EWjSsuHAYABy/4ZogFVZf7Kl4OziaLhXs+QKyzrViBYwDFotu5hmSlT7h3i/DeIA+GiGxMV39LE92oBZgVYvGr73uCfzJ/BNp94Qft28/63PgoCcyx0FzndC+T1t3R9dbzcR6ttQ8Qn7b8cO/kXI5YlXRHnECMDqbCeq3vVFSTlJPKW+JTXB2olR7cX9P5jlAD2u5B5YiqA="
    - secure: "RCujlmfPFak/A3vLCPJbExXWa9MfNEkwS8YPY9y76onZ9ENCfPNyw6oDxg6FJ5W7Y0j8QnyGoclulT2Fb2mxOHqTb8jIiF1xCp8UQxEtOFbbYXYwNHuGuunxaPBxdayvlIN988v6WqDUezSEXd9WXTCxWTxUnJd4tHP/6BeBvbPxcVSZ7pLKs/eWDpQfGrEb8B2VPTCdvko9xqHgvHcD5jBFEQsO+db2sVWC1x5W2xGH6ePKsLtgbHLqw/AVf5ic3kYLITFeWthSRvhNh1De2NRhNsNMAb4TBa1Ko4M5sKhW6ufMBNdSIUUXfU+sv7VlGxGtutKskogoMUIk29c93ysLRjd1NHVcQsyfJEVYA3FRjI+XvgKhC6r1xSoKMh8qV3Ruh9T5xDdQNg6rrkbKPdXX7SMA2sW/rMCH2YHWBYgUtJ7I/4TTmzSDScwkJKcKCYxIeLA7tUkSGaUwURolovzwta/kc5izjLv85f/FwATA5UhOKxhVaH/u+4f5bgrkQKZGuuDPxGi8xB44+3I0Nq2SUmNl3wA6KUnUWpV+wgEmov1kFBkvFNygdi8RxzMMIaN1TM3oIsDDNo26ZypN2m4xHAHO2r1App3fQpoPYYFHQaZtffbWHEYuzxyAGkG3crs1SSe8UwRkoYkvUlwjopvjE5xUF46W4+LAL+yH92Y="


# skip the `go get` stuff, since we do all of that in Docker
install: true

before_script:
  - export

script:
  - ./travis-build.sh
