
FROM golang:1.8-alpine

LABEL MAINTAINER="Michael Laccetti <michael@laccetti.com>"

RUN mkdir -p /go/src/github.com/mlaccetti/dns01-exec-plugin-r53 && \
  apk add --no-cache bash gcc git musl-dev libc-dev

VOLUME /go/src/github.com/mlaccetti/dns01-exec-plugin-r53

WORKDIR /go/src/github.com/mlaccetti/dns01-exec-plugin-r53

ENV GOOS=linux GOPATH=/go

ENTRYPOINT ["/go/src/github.com/mlaccetti/dns01-exec-plugin-r53/docker-entrypoint.sh"]
